[project]
name = "books-to-scrape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
    "beautifulsoup4>=4.13.4",
    "pandas>=2.2.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.10",
]
