name: Run scrape

on: 
  workflow_dispatch:
    inputs:
      n_books:
        description: Number of books to scrape
        required: false

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run scrape
        run: |
          run: |
            if [ ${{ github.event.inputs.n_books }} == 'all' ]; then
              echo "Will scrape all"
            else
              echo "Will scrape ${{ github.event.inputs.n_books }}"
            fi

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: scrape
          path: outputs/
